import PDFDocument from 'pdfkit';
import { ReportDetails } from '../types/report';

export const PDFGenerator = {
  /**
   * Generates a PDF buffer for report details
   */
  async generatePDF(report: ReportDetails): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          margin: 50,
          bufferPages: true,
          size: 'A4',
        });

        const chunks: Buffer[] = [];
        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', (err) => reject(err));

        // 1. Template-based Color Theme Mapping
        const theme = report.template || 'professional';
        let primaryColor = '#4F46E5'; // Indigo
        let secondaryColor = '#4F46E5';
        const headerTextColor = '#FFFFFF';
        let highlightColor = '#F3F4F6';

        if (theme === 'minimal') {
          primaryColor = '#1E293B'; // Slate
          secondaryColor = '#64748B';
          highlightColor = '#F8FAFC';
        } else if (theme === 'executive') {
          primaryColor = '#0F172A'; // Navy
          secondaryColor = '#D97706'; // Amber accent
          highlightColor = '#FFFBEB';
        }

        // --- Document Header ---
        doc.rect(0, 0, 595.28, 100).fill(primaryColor);
        doc.fillColor(headerTextColor)
          .font('Helvetica-Bold')
          .fontSize(20)
          .text(report.name, 50, 30);

        doc.fillColor(theme === 'executive' ? secondaryColor : '#E0E7FF')
          .font('Helvetica')
          .fontSize(10)
          .text('ExpenseIQ Financial Reporting Center', 50, 56);

        // --- Metadata Info Block ---
        doc.fillColor('#334155').font('Helvetica-Bold').fontSize(10).text('Generated By: ', 50, 120);
        doc.font('Helvetica').text(report.userName, 130, 120);

        doc.font('Helvetica-Bold').text('Generated On: ', 50, 135);
        doc.font('Helvetica').text(new Date(report.generatedAt).toLocaleString(), 130, 135);

        doc.font('Helvetica-Bold').text('Report Type: ', 50, 150);
        doc.font('Helvetica').text(report.type, 130, 150);

        // Filters Description block
        doc.rect(50, 175, 495, 40).fill(highlightColor);
        doc.fillColor('#1E293B').font('Helvetica-Bold').fontSize(9).text('Applied Filters:', 60, 182);
        
        const filterDetails: string[] = [];
        const f = report.filters;
        if (f.startDate) filterDetails.push(`Start: ${new Date(f.startDate).toLocaleDateString()}`);
        if (f.endDate) filterDetails.push(`End: ${new Date(f.endDate).toLocaleDateString()}`);
        if (f.types && f.types.length > 0) filterDetails.push(`Types: ${f.types.join(',')}`);
        if (f.paymentMethods && f.paymentMethods.length > 0) filterDetails.push(`Methods: ${f.paymentMethods.join(',')}`);
        if (f.minAmount !== undefined) filterDetails.push(`Min: $${f.minAmount}`);
        if (f.maxAmount !== undefined) filterDetails.push(`Max: $${f.maxAmount}`);
        if (filterDetails.length === 0) filterDetails.push('None (All history records)');

        doc.fillColor('#475569')
          .font('Helvetica')
          .text(filterDetails.join(' | '), 60, 196, { width: 475 });

        // --- Summary Grid Blocks ---
        doc.fillColor(primaryColor).font('Helvetica-Bold').fontSize(13).text('Executive Financial Summary', 50, 235);
        doc.strokeColor('#E2E8F0').lineWidth(1).moveTo(50, 252).lineTo(545, 252).stroke();

        const s = report.summary;
        const gridX1 = 50;
        const gridX2 = 215;
        const gridX3 = 380;
        const gridW = 150;
        const gridH = 45;

        // Row 1
        drawSummaryBox(doc, gridX1, 265, gridW, gridH, 'Total Income', `$${s.totalIncome.toFixed(2)}`, primaryColor, highlightColor);
        drawSummaryBox(doc, gridX2, 265, gridW, gridH, 'Total Expense', `$${s.totalExpense.toFixed(2)}`, primaryColor, highlightColor);
        drawSummaryBox(doc, gridX3, 265, gridW, gridH, 'Net Balance', `$${s.netBalance.toFixed(2)}`, s.netBalance >= 0 ? '#10B981' : '#EF4444', s.netBalance >= 0 ? '#ECFDF5' : '#FEF2F2');

        // Row 2
        drawSummaryBox(doc, gridX1, 320, gridW, gridH, 'Savings Rate', `${s.savingsRate.toFixed(1)}%`, primaryColor, highlightColor);
        drawSummaryBox(doc, gridX2, 320, gridW, gridH, 'Daily Avg Spend', `$${s.averageDailySpend.toFixed(2)}`, primaryColor, highlightColor);
        drawSummaryBox(doc, gridX3, 320, gridW, gridH, 'Budget Utilization', `${s.budgetUtilization.toFixed(1)}%`, s.budgetUtilization > 100 ? '#EF4444' : primaryColor, s.budgetUtilization > 100 ? '#FEF2F2' : highlightColor);

        // --- Category breakdown list bar ---
        let currentY = 385;
        doc.fillColor(primaryColor).font('Helvetica-Bold').fontSize(13).text('Category Breakdown Distribution', 50, currentY);
        doc.strokeColor('#E2E8F0').lineWidth(1).moveTo(50, currentY + 16).lineTo(545, currentY + 16).stroke();

        currentY += 28;
        doc.fillColor('#475569').font('Helvetica-Bold').fontSize(9);
        doc.text('Category', 55, currentY);
        doc.text('Type', 200, currentY);
        doc.text('Amount', 320, currentY, { width: 80, align: 'right' });
        doc.text('Share %', 420, currentY, { width: 50, align: 'right' });
        doc.text('Count', 500, currentY, { width: 40, align: 'right' });

        doc.strokeColor('#CBD5E1').lineWidth(0.8).moveTo(50, currentY + 12).lineTo(545, currentY + 12).stroke();
        currentY += 18;

        const displayedCategories = report.categoryBreakdown.slice(0, 5); // display top 5 categories
        doc.font('Helvetica').fontSize(9).fillColor('#334155');

        for (const cat of displayedCategories) {
          doc.text(cat.name, 55, currentY);
          doc.text(cat.type, 200, currentY);
          doc.text(`$${cat.amount.toFixed(2)}`, 320, currentY, { width: 80, align: 'right' });
          doc.text(`${cat.percentage.toFixed(1)}%`, 420, currentY, { width: 50, align: 'right' });
          doc.text(String(cat.count), 500, currentY, { width: 40, align: 'right' });

          // Draw inline light progress bar line below
          doc.rect(55, currentY + 12, 485, 3).fill('#F1F5F9');
          doc.rect(55, currentY + 12, 485 * (cat.percentage / 100), 3).fill(cat.color || primaryColor);

          currentY += 22;
        }

        // --- Detailed transaction log table ---
        currentY += 15;
        doc.fillColor(primaryColor).font('Helvetica-Bold').fontSize(13).text('Detailed Transaction Logs', 50, currentY);
        doc.strokeColor('#E2E8F0').lineWidth(1).moveTo(50, currentY + 16).lineTo(545, currentY + 16).stroke();

        currentY += 28;
        doc.fillColor('#475569').font('Helvetica-Bold').fontSize(9);
        doc.text('Date', 55, currentY);
        doc.text('Title Description', 130, currentY);
        doc.text('Category', 300, currentY);
        doc.text('Type', 410, currentY);
        doc.text('Amount', 475, currentY, { width: 65, align: 'right' });

        doc.strokeColor('#CBD5E1').lineWidth(0.8).moveTo(50, currentY + 12).lineTo(545, currentY + 12).stroke();
        currentY += 18;

        doc.font('Helvetica').fontSize(8.5).fillColor('#334155');
        
        const displayedTransactions = report.transactions.slice(0, 10); // display top 10 items in first page limits
        for (const tx of displayedTransactions) {
          // Automatic page break prevention
          if (currentY > 730) {
            doc.addPage();
            currentY = 50;
            // Draw table headers again
            doc.fillColor('#475569').font('Helvetica-Bold').fontSize(9);
            doc.text('Date', 55, currentY);
            doc.text('Title Description', 130, currentY);
            doc.text('Category', 300, currentY);
            doc.text('Type', 410, currentY);
            doc.text('Amount', 475, currentY, { width: 65, align: 'right' });
            doc.strokeColor('#CBD5E1').lineWidth(0.8).moveTo(50, currentY + 12).lineTo(545, currentY + 12).stroke();
            currentY += 18;
            doc.font('Helvetica').fontSize(8.5).fillColor('#334155');
          }

          const txDateStr = new Date(tx.date).toLocaleDateString();
          doc.text(txDateStr, 55, currentY);
          doc.text(tx.title.substring(0, 30), 130, currentY);
          doc.text(tx.categoryName, 300, currentY);
          doc.text(tx.type, 410, currentY);
          
          doc.fillColor(tx.type === 'INCOME' ? '#10B981' : '#334155');
          doc.text(`$${tx.amount.toFixed(2)}`, 475, currentY, { width: 65, align: 'right' });
          doc.fillColor('#334155');

          doc.strokeColor('#F1F5F9').lineWidth(0.5).moveTo(50, currentY + 12).lineTo(545, currentY + 12).stroke();
          currentY += 18;
        }

        // --- Global Footer and Page Numbers ---
        const pageRange = doc.bufferedPageRange();
        for (let i = 0; i < pageRange.count; i++) {
          doc.switchToPage(i);
          doc.strokeColor('#E2E8F0').lineWidth(0.5).moveTo(50, 785).lineTo(545, 785).stroke();

          doc.fillColor('#94A3B8')
            .font('Helvetica')
            .fontSize(8)
            .text('ExpenseIQ Report Engine v1.0.0 • Confidential', 50, 792);

          doc.text(`Page ${i + 1} of ${pageRange.count}`, 470, 792, { align: 'right', width: 75 });
        }

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  },
};

// Summary metrics box drawing utility
function drawSummaryBox(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  w: number,
  h: number,
  label: string,
  value: string,
  primaryColor: string,
  bgColor: string
) {
  doc.rect(x, y, w, h).fill(bgColor);
  doc.rect(x, y, w, h).strokeColor('#E2E8F0').lineWidth(0.8).stroke();

  // Top accent border line
  doc.strokeColor(primaryColor).lineWidth(1.5).moveTo(x, y).lineTo(x + w, y).stroke();

  doc.fillColor('#64748B').font('Helvetica').fontSize(8).text(label.toUpperCase(), x + 10, y + 10);
  doc.fillColor(primaryColor).font('Helvetica-Bold').fontSize(12).text(value, x + 10, y + 23);
}
